### ISSUE TITLE
Link the 'Take Action' buttons to Legislator pages.

### ISSUE THREAD

**Issue by mherrero347** [climatecabinet/scorecard-search#16]
**expected**: When someone clicks the 'Take Action' button from the search module, they should be sent to the Legislator's personal page.

**current**: The 'Take Action' buttons don't do anything.

**steps to reproduce**:
1. Load the [search module](https://climatecabinet.github.io/scorecard-search/).
2. Select a state.
3. Try to click the 'Take Action' button of any legislator.

**Comment by mcchang** [comment]
@mherrero347 this seems like something we need for launch, right? Should I take a look at implementing?
