### ISSUE TITLE
Mobile 'Take Action' Button Vector

### ISSUE THREAD

**Issue by karanmotwanipro** [climatecabinet/scorecard-search#26]
@mherrero347 
Could you please replace the take action on mobile to be a square button? Here is the vector for it.
Thank you
<img width="741" alt="Screen Shot 2021-08-12 at 12 41 30 PM" src="https://user-images.githubusercontent.com/85572187/129647882-9a727a0b-844b-4915-b1bc-48479b48d50e.png">
![ActionButtonMobile](https://user-images.githubusercontent.com/85572187/129647888-88db9e16-c1eb-46c7-b2d9-d33e1953c7ba.png)

**Comment by karanmotwanipro** [comment]
@mcchang Hey Michael, I don't see the take action button vector on the mobile view. Can you confirm if they are live? Thanks

**Comment by mcchang** [comment]
@karanmotwanipro My change is live, but confirming that I also don't see the take action button.  Given the way we have the search app deployed in production it looks like it can't find the image file.  Let me see if I can fix this quickly 
![image](https://user-images.githubusercontent.com/66332/131509258-6b696f6c-c9d2-4b2c-8e33-5348227fefea.png)

**Comment by mcchang** [comment]
Still not fixed it looks like

**Comment by mcchang** [comment]
@karanmotwanipro ok, fixed now
